lib/construtora_lc_hiert_web/router.ex
defmodule ConstrutoraLcHiertWeb.Router do
  use ConstrutoraLcHiertWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug ConstrutoraLcHiert.Authentication.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug :put_layout, {ConstrutoraLcHiertWeb.LayoutView, :admin}
  end

  scope "/", ConstrutoraLcHiertWeb do
    pipe_through [:browser, :auth]

    get "/", HomeController, :index
    get "/quem-somos", AboutController, :index
    resources "/contato", ContactController, only: [:index, :create]

    scope "/imoveis" do
      get "/apartamentos", ApartmentController, :index
      get "/casas", HouseController, :index
      get "/lotes", LotController, :index
      get "/busca", SearchController, :index

      get "/:slug", PropertyController, :show
    end

    scope "/inscritos" do
      post "/", SubscriberController, :create
      get "/desinscrever/:id", UnsubscribeController, :index
      delete "/desinscrever/:id", UnsubscribeController, :delete
    end

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    get "/sitemap.xml", SitemapController, :index
  end

  scope "/admin", ConstrutoraLcHiertWeb, as: :admin do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/", Admin.PageController, :index

    resources "/inscritos", Admin.SubscriberController, only: [:index] do
      resources "/ativacao", Admin.Subscriber.ActivationController,
        only: [:create, :delete],
        singleton: true
    end

    resources "/usuarios", Admin.UserController
    resources "/comodidades", Admin.AmenityController, except: [:show]

    resources "/imoveis", Admin.PropertyController, except: [:show, :delete] do
      resources "/fotos", Admin.Property.ImageController,
        only: [:new, :create, :delete],
        singleton: true do
        resources "/destaque", Admin.Property.Image.FeaturedController, only: [:create]
      end
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/construtora_lc_hiert_web/views/shared_view.ex
defmodule ConstrutoraLcHiertWeb.SharedView do
  use ConstrutoraLcHiertWeb, :view
end

lib/construtora_lc_hiert_web/templates/shared/_footer.html.eex
<footer id="footer" class="footer-area bg-footer bg-opacity-black-80">
  <div class="footer-top pt-110 pb-80">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <div class="footer-widget">
            <h6 class="footer-titel">ENTRE EM CONTATO</h6>
            <ul class="footer-address">
              <li>
                <div class="address-icon">
                  <%= icon_tag(@conn, "location") %>
                </div>
                <div class="address-info">
                  <span>Rua Carlos Barbosa, 1640</span>
                  <span>Vila Industrial, Toledo-PR</span>
                </div>
              </li>
              <li>
                <div class="address-icon">
                  <%= icon_tag(@conn, "phone") %>
                </div>
                <div class="address-info">
                  <span>Telefone: (45) 3055-4488</span>
                  <span>Whatsapp: (45) 99970-5998</span>
                </div>
              </li>
              <li>
                <div class="address-icon">
                  <%= icon_tag(@conn, "world") %>
                </div>
                <div class="address-info">
                  <span>
                    <a href="//www.construtoralchiert.com.br" target="_blank" rel="noopener">
                      www.construtoralchiert.com.br
                    </a>
                  </span>
                  <span>
                    <a href="//www.facebook.com/construtoralchiert" target="_blank" rel="noopener">
                      www.facebook.com/construtoralchiert
                    </a>
                  </span>
                </div>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-lg-6 col-md-5 hidden-sm col-xs-12">
          <div class="footer-widget middle">
            <h6 class="footer-titel">ÚLTIMOS IMÓVEIS</h6>
            <ul class="footer-latest-news">

              <%= if length(@footer_properties) == 0 do %>
                <li>
                  <div class="latest-news-info">
                    <p>Nenhum resultado encontrado para esta categoria :(</p>
                  </div>
                </li>
              <% else %>
                <%= for property <- @footer_properties do %>
                  <li>
                    <div class="latest-news-image">
                      <a href="<%= Routes.property_path(@conn, :show, property.slug) %>">
                        <img
                          src="<%= image_url(property.images, %{width: 82, height: 53}) %>"
                          alt="<%= ConstrutoraLcHiertWeb.PropertyView.full_address(property) %>">
                      </a>
                    </div>
                    <div class="latest-news-info">
                      <h6>
                        <a href="<%= Routes.property_path(@conn, :show, property.slug) %>">
                          <%= ConstrutoraLcHiertWeb.PropertyView.translate_type(property.type) %>
                          em <%= ConstrutoraLcHiertWeb.PropertyView.city(property) %>
                        </a>
                      </h6>
                      <p>
                        <%= ConstrutoraLcHiertWeb.PropertyView.property_information(property) %>
                      </p>
                    </div>
                  </li>
                <% end %>
              <% end %>

            </ul>
          </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
          <div class="footer-widget">
            <h6 class="footer-titel">ENVIE UMA MENSAGEM</h6>
            <div class="footer-contact">
              <p class="js-ajax-form-animation-response"></p>

              <%= form_for @conn, Routes.contact_path(@conn, :create), [class: 'js-ajax-form-animation'], fn f -> %>
                <%= text_input f, :name, placeholder: "Digite seu nome...", title: "Nome", required: true %>
                <%= email_input f, :email, placeholder: "Digite seu e-mail...", title: "E-mail", required: true %>
                <%= textarea f, :message, placeholder: "Escreva sua mensagem...", title: "Mensagem", required: true %>

                <%= submit "Enviar" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

lib/construtora_lc_hiert_web/templates/shared/_header.html.eex
<header class="header-area header-wrapper">
  <div class="header-top-bar bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="logo">
            <a href="<%= Routes.home_path(@conn, :index) %>">
              <img src="https://ik.imagekit.io/ricardoruwer/lchiert/images/logo.png" alt="Construtora LC Hiert">
            </a>
          </div>
        </div>
        <div class="col-md-6 hidden-sm hidden-xs">
          <div class="company-info clearfix">
            <div class="company-info-item">
              <div class="header-icon">
                <%= icon_tag(@conn, "phone") %>
              </div>
              <div class="header-info">
                <h6>(45) 3055-4488</h6>
                <p>Aberto das 8:00 - 12:00 e 13:30 - 17:30</p>
              </div>
            </div>
            <div class="company-info-item">
              <div class="header-icon">
                <%= icon_tag(@conn, "whatsapp") %>
              </div>
              <div class="header-info">
                <h6><a href="http://api.whatsapp.com/send?1=pt_BR&phone=5545999705998">(45) 99970-5998</a></h6>
                <p>Mande um WhatsApp</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="header-search clearfix">
            <%= form_for @conn, Routes.search_path(@conn, :index), [method: :get], fn f -> %>
              <%= submit icon_tag(@conn, "search"), class: "search-icon" %>
              <%= text_input f, :q, placeholder: "Procurar...", value: @conn.params["q"], required: true %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="sticky-header" class="header-middle-area transparent-header hidden-xs">
    <div class="container">
      <div class="full-width-mega-drop-menu">
        <div class="row">
          <div class="col-md-12">
            <div class="sticky-logo">
              <a href="<%= Routes.home_path(@conn, :index) %>">
                <img src="https://ik.imagekit.io/ricardoruwer/lchiert/images/logo.png" alt="Construtora LC Hiert">
              </a>
            </div>
            <nav id="primary-menu">
              <ul class="main-menu text-center">
                <%= render("_menu_items.html", assigns) %>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<%= render("_mobile_menu.html", assigns) %>

lib/construtora_lc_hiert_web/templates/shared/_menu_items.html.eex
<li><a href="<%= Routes.home_path(@conn, :index) %>">Home</a></li>
<li><a href="<%= Routes.about_path(@conn, :index) %>">Quem somos</a></li>
<li><a href="<%= Routes.apartment_path(@conn, :index) %>">Apartamentos</a></li>
<li><a href="<%= Routes.house_path(@conn, :index) %>">Casas</a></li>
<li><a href="<%= Routes.lot_path(@conn, :index) %>">Lotes</a></li>
<li><a href="<%= Routes.contact_path(@conn, :index) %>">Fale conosco</a></li>

lib/construtora_lc_hiert_web/templates/shared/_mobile_menu.html.eex
<div class="mobile-menu-area visible-xs">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="mobile-menu">
          <nav id="dropdown">
            <ul><%= render("_menu_items.html", assigns) %></ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

lib/construtora_lc_hiert_web/templates/shared/_no_results_found.html.eex
<div class="col-md-12 text-center">
  <div class="alert no-results">
    <%= icon_tag(@conn, "sad-face") %>
    <p>Desculpe, não foi encontrado nenhum resultado.</p>
  </div>
</div>

lib/construtora_lc_hiert_web/templates/shared/_search.html.eex
<div class="row">
  <%= form_for @conn, Routes.search_path(@conn, :index), [method: :get], fn f -> %>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item custom-select">
        <%= select f, :city, @cities, class: "selectpicker", title: "Cidade" %>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item custom-select">
        <%= select f, :neighborhood, @neighborhoods, class: "selectpicker", title: "Bairro" %>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item">
        <%= text_input f, :min_area, placeholder: "Área mínima", title: "Área mínima" %>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item">
        <%= text_input f, :max_area, placeholder: "Área máxima", title: "Área máxima" %>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item  custom-select">
        <%=
          select f,
            :qty_rooms,
            ConstrutoraLcHiertWeb.PropertyView.property_rooms_for_select(),
            class: "selectpicker",
            title: "Qtde. Quartos"
        %>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item custom-select">
        <%=
          select f,
            :qty_bathrooms,
            ConstrutoraLcHiertWeb.PropertyView.property_bathrooms_for_select(),
            class: "selectpicker",
            title: "Qtde. Banheiros"
        %>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item">
        <div class="find-home-item custom-select">
          <%=
            select f,
              :type,
              ConstrutoraLcHiertWeb.PropertyView.property_types_for_select(),
              class: "selectpicker",
              title: "Tipo"
          %>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="find-home-item">
        <%= submit "BUSCAR", class: "button-1 btn-block btn-hover-1" %>
      </div>
    </div>
  <% end %>
</div>

lib/construtora_lc_hiert_web/templates/shared/_services.html.eex
<div class="services-area pt-70 pb-70">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-title-2 text-center">
          <h2>SERVIÇOS</h2>
          <p>
            Trabalhamos com venda de imóveis: casas, apartamentos e lotes em Toledo-PR e região.
          </p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="col-md-4 col-xs-12">
          <div class="service-item">
            <div class="service-item-image">
              <img src="https://ik.imagekit.io/ricardoruwer/lchiert/images/service/apto.jpg" alt="Venda de apartamentos">
            </div>
            <div class="service-item-info">
              <h5>Venda de Apartamentos</h5>
              <p>Apartamentos ideais para você e sua família viver com muito conforto e segurança</p>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-xs-12">
          <div class="service-item">
            <div class="service-item-image">
              <img src="https://ik.imagekit.io/ricardoruwer/lchiert/images/service/casa.jpg" alt="Venda de casas">
            </div>
            <div class="service-item-info">
              <h5>Venda de Casas</h5>
              <p>Você merece uma casa para passar mais momentos agradáveis com sua família</p>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-xs-12">
          <div class="service-item">
            <div class="service-item-image">
              <img src="https://ik.imagekit.io/ricardoruwer/lchiert/images/service/lote.jpg" alt="Venda de lotes">
            </div>
            <div class="service-item-info">
              <h5>Venda de Lotes</h5>
              <p>Venha conhecer nossas opções em lotes em Toledo e região e invista no seu futuro</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/construtora_lc_hiert_web/templates/shared/_subscribe.html.eex
<div class="subscribe-area bg-blue call-to-bg plr-140 ptb-50">
  <div class="container-fluid">
    <div class="row">

      <div class="col-md-3 col-sm-4 col-xs-12">
        <div class="section-title text-white">
          <svg class="coming-home">
            <use xlink:href="<%= Routes.static_path(@conn, "/images/coming_home.svg") %>#coming_home" />
          </svg>

          <h4>SAIBA DE TODAS</h4>
          <h3>NOVIDADES</h3>
        </div>
      </div>

      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="subscribe">
          <p class="subscribe-title">
            Receba um email toda vez que adicionarmos um novo imóvel em nosso site:
          </p>

          <p class="js-ajax-form-animation-response subscribe-response"></p>

          <%= form_for @conn, Routes.subscriber_path(@conn, :create), [class: 'js-ajax-form-animation'], fn f -> %>
            <%= email_input f, :email, placeholder: "Digite seu e-mail aqui...", title: "E-mail", required: true %>
            <%= submit "Cadastrar" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>