lib/construtora_lc_hiert_web/router.ex
defmodule ConstrutoraLcHiertWeb.Router do
  use ConstrutoraLcHiertWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug ConstrutoraLcHiert.Authentication.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug :put_layout, {ConstrutoraLcHiertWeb.LayoutView, :admin}
  end

  scope "/", ConstrutoraLcHiertWeb do
    pipe_through [:browser, :auth]

    get "/", HomeController, :index
    get "/quem-somos", AboutController, :index
    resources "/contato", ContactController, only: [:index, :create]

    scope "/imoveis" do
      get "/apartamentos", ApartmentController, :index
      get "/casas", HouseController, :index
      get "/lotes", LotController, :index
      get "/busca", SearchController, :index

      get "/:slug", PropertyController, :show
    end

    scope "/inscritos" do
      post "/", SubscriberController, :create
      get "/desinscrever/:id", UnsubscribeController, :index
      delete "/desinscrever/:id", UnsubscribeController, :delete
    end

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    get "/sitemap.xml", SitemapController, :index
  end

  scope "/admin", ConstrutoraLcHiertWeb, as: :admin do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/", Admin.PageController, :index

    resources "/inscritos", Admin.SubscriberController, only: [:index] do
      resources "/ativacao", Admin.Subscriber.ActivationController,
        only: [:create, :delete],
        singleton: true
    end

    resources "/usuarios", Admin.UserController
    resources "/comodidades", Admin.AmenityController, except: [:show]

    resources "/imoveis", Admin.PropertyController, except: [:show, :delete] do
      resources "/fotos", Admin.Property.ImageController,
        only: [:new, :create, :delete],
        singleton: true do
        resources "/destaque", Admin.Property.Image.FeaturedController, only: [:create]
      end
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/construtora_lc_hiert_web/views/layout_view.ex
defmodule ConstrutoraLcHiertWeb.LayoutView do
  use ConstrutoraLcHiertWeb, :view

  alias ConstrutoraLcHiertWeb.PageTitle
  alias ConstrutoraLcHiertWeb.OpenGraph

  def page_title(conn) do
    view = view_module(conn)
    action = action_name(conn)
    PageTitle.for({view, action, conn.assigns})
  end

  def open_graph(conn) do
    view = view_module(conn)
    action = action_name(conn)
    OpenGraph.for({view, action, conn})
  end

  def current_user(conn) do
    Guardian.Plug.current_resource(conn)
  end

  def active_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])

    if path == current_path do
      "active"
    else
      nil
    end
  end

  @doc """
  Generates path for the JavaScript view we want to use in this combination of
  controller/action.
  """
  def js_view_path(conn) do
    [controller_name(conn), action_name(conn)]
    |> Enum.join("/")
  end

  defp controller_name(conn) do
    conn
    |> Phoenix.Controller.controller_module()
    |> to_string
    |> String.split(".")
    |> List.delete_at(0)
    |> List.delete_at(0)
    |> Enum.join("/")
    |> String.replace("Controller", "")
    |> String.downcase()
  end
end

lib/construtora_lc_hiert_web/templates/layout/admin.html.eex
<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>

    <title>Admin · Construtora LC Hiert</title>

    <link rel="shortcut icon" type="image/x-icon" href="<%= Routes.static_path(@conn, "/favicon.ico") %>">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/admin.css") %>"/>
  </head>

  <body data-js-view-path="<%= js_view_path(@conn) %>">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Navegação</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= Routes.home_path(@conn, :index) %>">Construtora LC Hiert</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="<%= Routes.admin_user_path(@conn, :show, current_user(@conn).id) %>">
                <%= current_user(@conn).username %>
              </a>
            </li>
            <li><%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete %></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="<%= active_class(@conn, Routes.admin_page_path(@conn, :index)) %>">
              <a href="<%= Routes.admin_page_path(@conn, :index) %>">Dashboard</a>
            </li>
          </ul>
          <ul class="nav nav-sidebar">
            <li class="<%= active_class(@conn, Routes.admin_property_path(@conn, :index)) %>">
              <a href="<%= Routes.admin_property_path(@conn, :index) %>">Imóveis</a>
            </li>
            <li class="<%= active_class(@conn, Routes.admin_amenity_path(@conn, :index)) %>">
              <a href="<%= Routes.admin_amenity_path(@conn, :index) %>">Comodidades</a>
            </li>
            <li class="<%= active_class(@conn, Routes.admin_subscriber_path(@conn, :index)) %>">
              <a href="<%= Routes.admin_subscriber_path(@conn, :index) %>">Inscritos</a>
            </li>
          </ul>
          <ul class="nav nav-sidebar">
            <li class="<%= active_class(@conn, Routes.admin_user_path(@conn, :index)) %>">
              <a href="<%= Routes.admin_user_path(@conn, :index) %>">Usuários</a>
            </li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= if info = get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= info %></p>
          <% end %>
          <%= if error = get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert"><%= error %></p>
          <% end %>

          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>

lib/construtora_lc_hiert_web/templates/layout/app.html.eex
<!doctype html>
<html class="no-js" lang="pt-BR" dir="ltr">

<head>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-16760908-7"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-16760908-7');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="description" content="Construtora LC Hiert - Venda de imóveis: casas, apartamentos e lotes em Toledo - PR.">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= page_title(@conn) %></title>

  <link rel="shortcut icon" type="image/x-icon" href="<%= Routes.static_path(@conn, "/favicon.ico") %>">
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">

  <%= open_graph(@conn) %>

  <link rel="preload" as="font" href="<%= Routes.static_path(@conn, "/fonts/montserrat-latin-300.woff2") %>" type="font/woff2" crossorigin="anonymous">
  <link rel="preload" as="font" href="<%= Routes.static_path(@conn, "/fonts/montserrat-latin-400.woff2") %>" type="font/woff2" crossorigin="anonymous">

  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "LocalBusiness",
    "image": "https://ik.imagekit.io/ricardoruwer/lchiert/images/logo.png",
    "telephone": "(45) 3055-4488",
    "email": "construcao.lc@gmail.com",
    "url": "https://www.construtoralchiert.com.br",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Rua Carlos Barbosa, 1640",
      "addressLocality": "Toledo",
      "addressRegion": "PR"
    },
    "potentialAction": {
      "@type": "SearchAction",
      "target": "https://construtoralchiert.com/imoveis/busca?q={search_term_string}",
      "query-input": "required name=search_term_string"
    }
  }
  </script>
</head>

<body data-js-view-path="<%= js_view_path(@conn) %>">
  <!--[if lt IE 8]>
    <p class="browserupgrade">Você está usando um navegador muito antigo. Por favor, <a href="http://browsehappy.com/">atualize seu navegador</a> para ter uma melhor experiência.</p>
  <![endif]-->

  <div class="wrapper">
    <%= render(ConstrutoraLcHiertWeb.SharedView, "_header.html", assigns) %>

    <%= render @view_module, @view_template, assigns %>

    <%= render(ConstrutoraLcHiertWeb.SharedView, "_footer.html", assigns) %>
  </div>

  <script type="text/javascript" async src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/construtora_lc_hiert_web/templates/layout/email.html.eex
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Construtora LC Hiert</title>
    <style>
      /* -------------------------------------
          GLOBAL RESETS
      ------------------------------------- */
      img {
        border: none;
        -ms-interpolation-mode: bicubic;
        max-width: 100%;
      }

      body {
        background-color: #f6f6f6;
        font-family: sans-serif;
        -webkit-font-smoothing: antialiased;
        font-size: 14px;
        line-height: 1.4;
        margin: 0;
        padding: 0;
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%;
      }

      table {
        border-collapse: separate;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
        width: 100%; }
        table td {
          font-family: sans-serif;
          font-size: 14px;
          vertical-align: top;
      }

      /* -------------------------------------
          BODY & CONTAINER
      ------------------------------------- */

      .body {
        background-color: #f6f6f6;
        width: 100%;
      }

      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
        display: block;
        margin: 0 auto !important;
        /* makes it centered */
        max-width: 580px;
        padding: 10px;
        width: 580px;
      }

      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
        box-sizing: border-box;
        display: block;
        margin: 0 auto;
        max-width: 580px;
        padding: 10px;
      }

      /* -------------------------------------
          HEADER, FOOTER, MAIN
      ------------------------------------- */
      .main {
        background: #ffffff;
        border-radius: 3px;
        width: 100%;
      }

      .wrapper {
        box-sizing: border-box;
        padding: 20px;
      }

      .content-block {
        padding-bottom: 10px;
        padding-top: 10px;
      }

      .unsubscribe {
        color: #bbb;
        font-size: 11px;
        text-align: center;
        margin-top: 40px;
        margin-bottom: 0;
      }

      .unsubscribe a {
        color: #aaa;
      }

      .footer {
        clear: both;
        margin-top: 10px;
        text-align: center;
        width: 100%;
      }
        .footer td,
        .footer p,
        .footer span,
        .footer a {
          color: #999999;
          font-size: 12px;
          text-align: center;
      }

      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1,
      h2,
      h3,
      h4 {
        color: #000000;
        font-family: sans-serif;
        font-weight: 400;
        line-height: 1.4;
        margin: 0;
        margin-bottom: 30px;
      }

      h1 {
        font-size: 35px;
        font-weight: 300;
        text-align: center;
        text-transform: capitalize;
      }

      p,
      ul,
      ol {
        font-family: sans-serif;
        font-size: 14px;
        font-weight: normal;
        margin: 0;
        margin-bottom: 15px;
      }
        p li,
        ul li,
        ol li {
          list-style-position: inside;
          margin-left: 5px;
      }

      a {
        color: #3498db;
        text-decoration: underline;
      }

      /* -------------------------------------
          BUTTONS
      ------------------------------------- */
      .btn {
        box-sizing: border-box;
        width: 100%; }
        .btn > tbody > tr > td {
          padding-bottom: 15px; }
        .btn table {
          width: auto;
      }
        .btn table td {
          background-color: #ffffff;
          border-radius: 5px;
          text-align: center;
      }
        .btn a {
          background-color: #ffffff;
          border: solid 1px #3498db;
          border-radius: 5px;
          box-sizing: border-box;
          color: #3498db;
          cursor: pointer;
          display: inline-block;
          font-size: 14px;
          font-weight: bold;
          margin: 0;
          padding: 12px 25px;
          text-decoration: none;
      }

      .btn-primary table td {
        background-color: #3498db;
      }

      .btn-primary a {
        background-color: #3498db;
        border-color: #3498db;
        color: #ffffff;
      }

      /* -------------------------------------
          OTHER STYLES THAT MIGHT BE USEFUL
      ------------------------------------- */
      .last {
        margin-bottom: 0;
      }

      .first {
        margin-top: 0;
      }

      .align-center {
        text-align: center;
      }

      .align-right {
        text-align: right;
      }

      .align-left {
        text-align: left;
      }

      .clear {
        clear: both;
      }

      .mt0 {
        margin-top: 0;
      }

      .mb0 {
        margin-bottom: 0;
      }

      .powered-by a {
        text-decoration: none;
      }

      hr {
        border: 0;
        border-bottom: 1px solid #f6f6f6;
        margin: 20px 0;
      }

      /* -------------------------------------
          RESPONSIVE AND MOBILE FRIENDLY STYLES
      ------------------------------------- */
      @media only screen and (max-width: 620px) {
        table[class=body] h1 {
          font-size: 28px !important;
          margin-bottom: 10px !important;
        }
        table[class=body] p,
        table[class=body] ul,
        table[class=body] ol,
        table[class=body] td,
        table[class=body] span,
        table[class=body] a {
          font-size: 16px !important;
        }
        table[class=body] .wrapper,
        table[class=body] .article {
          padding: 10px !important;
        }
        table[class=body] .content {
          padding: 0 !important;
        }
        table[class=body] .container {
          padding: 0 !important;
          width: 100% !important;
        }
        table[class=body] .main {
          border-left-width: 0 !important;
          border-radius: 0 !important;
          border-right-width: 0 !important;
        }
        table[class=body] .btn table {
          width: 100% !important;
        }
        table[class=body] .btn a {
          width: 100% !important;
        }
        table[class=body] .img-responsive {
          height: auto !important;
          max-width: 100% !important;
          width: auto !important;
        }
      }

      /* -------------------------------------
          PRESERVE THESE STYLES IN THE HEAD
      ------------------------------------- */
      @media all {
        .ExternalClass {
          width: 100%;
        }
        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
          line-height: 100%;
        }
        .apple-link a {
          color: inherit !important;
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          text-decoration: none !important;
        }
        .btn-primary table td:hover {
          background-color: #34495e !important;
        }
        .btn-primary a:hover {
          background-color: #34495e !important;
          border-color: #34495e !important;
        }
      }

    </style>
  </head>

  <body class="">
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <td>&nbsp;</td>
        <td class="container">
          <div class="content">

            <table role="presentation" class="main">
              <tr>
                <td class="wrapper">
                  <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td>
                        <%= render @view_module, @view_template, assigns %>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>

            <div class="footer">
              <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <span class="apple-link">Construtora LC Hiert</span>
                    -
                    <a href="https://www.construtoralchiert.com.br">www.construtoralchiert.com.br</a>
                    <br>
                    Rua Carlos Barbosa, 1640, Toledo, PR.
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </body>
</html>